spring:
  h2:
    console:
      enabled: true
  application:
    name: teach-me
  datasource:
    driver-class-name: org.postgresql.Driver
    username: soajudhvqnbzcr
    password: b3f4b917cace9181ff3fd379fe66e90ba5af23d77c335bd240f3a052739e39ff
    url: jdbc:postgresql://ec2-46-137-113-157.eu-west-1.compute.amazonaws.com:5432/d40djll15cp8oo
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/liquidbase-changelog.xml