spring:
  h2:
    console:
      enabled: true
  application:
    name: actor-its-me
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: od3FQGcT
    url: jdbc:postgresql://localhost:5432/ActorService
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/liquidbase-changelog.xml